import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

type Props = {
  title: string
}

export default function Home({title = "Welcome react nextjs!"}:Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {title}
      </div>
    </div>
  )
}
